version: '3.8'
services:
  db:
    image: postgres:15-alpine  # Use the official PostgreSQL image
    container_name: postgres-db
    environment:
      POSTGRES_USER: cepuii          # Database username
      POSTGRES_PASSWORD: cepuii  # Database password
      POSTGRES_DB: opal-db        # Default database name
    ports:
      - "5432:5432"                  # Expose PostgreSQL to the host
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist data
volumes:
  postgres-data:                     # Named volume for data persistence
